
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fabricio 
  password: PostgreSQL_Role_Password

development:
  <<: *default
  database: api_ecommerce_rails_development

test:
  <<: *default
  database: api_ecommerce_rails_test

production:
  <<: *default
  database: api_ecommerce_rails_production
  username: api_ecommerce_rails
  password: <%= ENV['API_ECOMMERCE_RAILS_DATABASE_PASSWORD'] %>
